### ISSUE TITLE
Request to update the package on PyPI

### ISSUE THREAD

**Issue by myl7** [DaRealFreak/saucenao#3]
After `pip install SauceNAO`, I found that the package on PyPI is `1.0.4.post1`, while the latest release in the repo is `1.0.4`. Cound you update the package on PyPI?

**Comment by DaRealFreak** [comment]
the post release is actually the newer one, but I created the 1.0.4 version release too late in github (created the post release to include the updated README file in the PyPI release).
I'm going to create a 1.0.5 release for your change, so both will be updated to 1.0.5 later today.

**Comment by DaRealFreak** [comment]
v1.0.5 is now released, thanks again for your PR
https://pypi.org/project/SauceNAO/1.0.5/
