### ISSUE TITLE
Worker doesn't return any results

### ISSUE THREAD

**Issue by Shiska** [DaRealFreak/saucenao#4]
In [Line 43 of worker.py](https://github.com/DaRealFreak/saucenao/blob/master/saucenao/worker.py#L43) it checks _**self.__move_to_categories**_ but that is always true since it is a method, I guess it should be **_self.move_to_categories_** instead so it actually yields the results if set to False

Correct me if I missed something

**Comment by DaRealFreak** [comment]
good find, thanks for already finding what the problem was, should be fixed with version 1.0.6
