### ISSUE TITLE
Not able to use BytesIO objects for files

### ISSUE THREAD

**Issue by penn5** [DaRealFreak/saucenao#5]
__get_http_data should accept already existing `file` objects, and simply read them. It should also accept `bytes` objects, and pass them through without even reading.

**Comment by DaRealFreak** [comment]
sorry for the delay.
I've added an additional function check_file_object which you can now call with any BinaryIO type argument (f.e. the open resource or io.BytesIO).

Gonna wait until SauceNAO is fully working again (it is throwing a 502 for me currently) for the unit tests and would release it with the new version
